---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/Jj1910/flux2-monitoring-example.git
