apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - headlamp
  - metrics-server
  - headlamp-repo
  - longhorn
  - longhorn-repo
  - kube-prometheus-stack-repo
  - kube-prometheus-stack
  - metallb-repo
  - metallb
  - metallb-config
