apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/headlamp

namePrefix: dev-

patches:
  - target:
      kind: HelmRelease
      name: headlamp
    patch: |
    spec:
      chart:
        spec:
          sourceRef:
            name: dev-headlamp
