apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp-ingress
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host("headlamp.kube.justinschoenfeld.com")
    kind: Rule
    services:
    - name: dev-flux-headlamp-release
      port: 80
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-headlamp-system
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-headlamp-repo
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: infrastructure/base/headlamp
  prune: true
  wait: true

  namePrefix: dev-flux-

  patches:
  - target:
      kind: HelmRelease
      name: headlamp-release
    patch: |-
      - op: replace
        path: /spec/chart/spec/version
        value: 0.44.0

      - op: add
        path: /spec/values
        value:
          replicaCount: 1
          serviceAccount:
            create: true
            name: "headlamp-sa"
          #service:
          #  type: NodePort
          #  port: 80
          #  nodePort: 30003
          #  type: LoadBalancer
          #Flux Plugin
          config:
            pluginsDir: /build/plugins
          initContainers:
            - command:
                - /bin/sh
                - -c
                - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/ && chown -R 100:101 /build
              image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
              imagePullPolicy: Always
              name: headlamp-plugins
              securityContext:
                runAsNonRoot: false
                privileged: false
                runAsUser: 0
                runAsGroup: 0
              volumeMounts:
                - mountPath: /build/plugins
                  name: headlamp-plugins
          volumeMounts:
            - mountPath: /build/plugins
              name: headlamp-plugins
          volumes:
            - name: headlamp-plugins
              emptyDir: {}        