apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubernetes-flux
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Jj1910/Kubernetes-Flux.git
  ref:
    branch: main
