apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-overlay
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: apps/overlay/dev
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shared-overlay
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: apps/overlay/shared
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: prometheus
    namespace: flux-system
  - kind: Deployment
    name: grafana
    namespace: flux-system
  interval: 1h
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: monitoring
  path: clusters/test
  prune: true
  wait: true
