apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 1m0s
  chart:
    spec:
      chart: prometheus
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus
        namespace: monitoring
  values:
    grafana:
      adminPassword: grafana
      persistence:
        enabled: false
      service:
        type: NodePort
        nodePort: 30004
    
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
      service:
        type: NodePort
        nodePort: 30090
    
    nodeExporter:
      enabled: true
    
    kubeStateMetrics:
      enabled: true
