apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: kube-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: headlamp
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: kube-system