apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/infra/kube-prometheus-stack

namePrefix: dev-

patches:
- target:
    kind: HelmRelease
    name: kube-prometheus-stack
  patch: |-
    - op: add
      path: /spec/values
      value: 
        grafana:
          adminUser: demo
          adminPassword: demopass
          service:
            type: NodePort
            nodePort: 30005
- target:
    kind: Namespace
    name: monitoring-system
  patch: |-
    - op: add
      path: /metadata
      value:
        name: monitoring-system
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged