apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp
  namespace: kube-system
spec:
  interval: 1h
  url: https://kubernetes-sigs.github.io/headlamp/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: kube-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: headlamp
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: kube-system
  values:
    replicaCount: 1
    serviceAccount:
      create: true
      name: "headlamp-sa"
    service:
      type: NodePort
      port: 80
      nodePort: 30003
