---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/Jj1910/flux2-monitoring-example.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: prometheus
    namespace: flux-system
  - kind: Deployment
    name: grafana
    namespace: flux-system
  interval: 1h
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: monitoring
  path: clusters/test
  prune: true
  wait: true

