apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/infra/headlamp

namePrefix: dev-

patches:
- target:
    kind: HelmRelease
    name: headlamp
  patch: |-
    - op: add
      path: /spec/values
      value:
        replicaCount: 1
        serviceAccount:
          create: true
          name: "headlamp-sa"
        service:
          type: NodePort
          port: 80
          nodePort: 30003
        #Flux Plugin
        config:
          pluginsDir: /build/plugins
        initContainers:
          - command:
              - /bin/sh
              - -c
              - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/ && chown -R 100:101 /build
            image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
            imagePullPolicy: Always
            name: headlamp-plugins
            securityContext:
              runAsNonRoot: false
              privileged: false
              runAsUser: 0
              runAsGroup: 0
            volumeMounts:
              - mountPath: /build/plugins
                name: headlamp-plugins
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
        volumes:
          - name: headlamp-plugins
            emptyDir: {}        
    